<?php

declare(strict_types=1);

// @codeCoverageIgnoreStart
namespace Tests\Support;

// This class is auto-generated by Codeception. Run `vendor/bin/codecept build` to regenerate.
trait _generated\ApiTesterActions
{
}
// @codeCoverageIgnoreEnd
